//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace Calculator
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Border = 0x7f020000;
            
            public const int Icon = 0x7f020001;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int tbValue = 0x7f04000e;
            
            public const int cmd1 = 0x7f04000f;
            
            public const int cmd2 = 0x7f040010;
            
            public const int cmd3 = 0x7f040011;
            
            public const int cmdDiv = 0x7f040012;
            
            public const int cmd4 = 0x7f040013;
            
            public const int cmd5 = 0x7f040014;
            
            public const int cmd6 = 0x7f040015;
            
            public const int cmdMul = 0x7f040016;
            
            public const int cmd7 = 0x7f040017;
            
            public const int cmd8 = 0x7f040018;
            
            public const int cmd9 = 0x7f040019;
            
            public const int cmdSub = 0x7f04001a;
            
            public const int cmd0 = 0x7f04001b;
            
            public const int cmdEnter = 0x7f04001c;
            
            public const int cmdClear = 0x7f04001d;
            
            public const int cmdAdd = 0x7f04001e;
        }
    }
}
