//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMenu
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int tbLog = 0x7f04000e;
            
            public const int item1 = 0x7f04000f;
            
            public const int firstGroup = 0x7f040010;
            
            public const int groupItem1 = 0x7f040011;
            
            public const int submenu = 0x7f040012;
            
            public const int submenu_item1 = 0x7f040013;
        }
        
        public sealed class Menus
        {
            
            public const int Menu = 0x7f050000;
        }
    }
}
