//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGps
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int txStatus = 0x7f04000e;
            
            public const int txProvider = 0x7f04000f;
            
            public const int txAccuracy = 0x7f040010;
            
            public const int txLatitude = 0x7f040011;
            
            public const int txLongtitude = 0x7f040012;
            
            public const int txAltitude = 0x7f040013;
            
            public const int txSpeed = 0x7f040014;
            
            public const int txExtra = 0x7f040015;
        }
    }
}
