//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBrowser
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Icon = 0x7f020000;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
            
            public const int OpenFileLayout = 0x7f030001;
            
            public const int OpenFileRowLayout = 0x7f030002;
        }
        
        public sealed class Ids
        {
            
            public const int txtInfo = 0x7f04000e;
            
            public const int cmdOpen = 0x7f04000f;
            
            public const int lbPath = 0x7f040010;
            
            public const int list = 0x7f040011;
            
            public const int txtRow = 0x7f040012;
        }
    }
}
