//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace SimpleActionBar
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int Alerts = 0x7f020000;
            
            public const int Icon = 0x7f020001;
        }
        
        public sealed class Layouts
        {
            
            public const int MainLayout = 0x7f030000;
        }
        
        public sealed class Ids
        {
            
            public const int tbLog = 0x7f04000e;
            
            public const int item1 = 0x7f04000f;
            
            public const int firstGroup = 0x7f040010;
            
            public const int groupItem1 = 0x7f040011;
            
            public const int submenu = 0x7f040012;
            
            public const int submenu_item1 = 0x7f040013;
        }
        
        public sealed class Menus
        {
            
            public const int Menu = 0x7f050000;
        }
    }
}
